- name: This playbook will build custom docker image to be used later as Jenkins Slave Node
  hosts: localhost
  tasks:
  - name: Delete Jenkins Slave Node Docker Image
    docker_image:
        docker_host: tcp://localhost:4243
        name: tektutor/jenkins-slave
        tag: latest
        force_absent: true
        source: local
        build:
          path: .

  - name: Build Jenkins Slave Node Docker Image
    docker_image:
        docker_host: tcp://localhost:4243
        name: tektutor/jenkins-slave
        tag: latest
        state: present
        source: build
        build:
          path: .
