#!/usr/bin/env groovy
pipeline {
    agent {
        label 'docker-slave'
    }
    stages {
        stage('Compile') {
            steps {
                script {
		    sh "cd ../CRM"
                    sh "mvn clean compile"
                }
            }
        }
        stage('Unit Test') {
            steps {
                script {
		    sh "cd ../CRM"
                    sh "mvn test"
                }
            }
        }
        stage('package') {
            steps {
                script {
		    sh "cd ../CRM"
                    sh "mvn package"
                }
            }
        }
        stage('Install') {
            steps {
                script {
		    sh "cd ../CRM"
                    sh "mvn install"
                }
            }
        }
    }
}
