#!/usr/bin/env groovy
pipeline {
    agent {
        label 'docker-slave'
    }
    stages {
       
        stage('Build docker image') {
            agent { label "controller" }
            steps {
                script {
                    dir("Day5/DevOpsPipeline") {
                    	sh "ansible-playbook build-dockerimage-playbook.yml"
		    }
                }
            }
        }
        stage('Compile') {
            steps {
                script {
                    dir("Day5/CRM") {
                    	sh "mvn clean compile"
		    }
                }
            }
        }
        stage('Unit Test') {
            steps {
                script {
		    dir("Day5/CRM") {
                    	sh "mvn test"
		    }
                }
            }
        }
        stage('package') {
            steps {
                script {
                    dir("Day5/CRM") {
                    	sh "mvn package"
	            }
                }
            }
        }
        stage('Install') {
            steps {
                script {
                    dir("Day5/CRM") {
                    	sh "mvn install"
		    }
                }
            }
        }
        stage('Deploy') {
            steps {
                script {
                    dir("Day5/CRM") {
                    	sh "mvn deploy"
		    }
                }
            }
        }
    }
}
